services:
  api:
    environment:
      ALLOWED_HOSTS: "task.abcvip.site,148.113.10.170,localhost,127.0.0.1"
      CORS_ALLOWED_ORIGINS: "https://task.abcvip.site,https://148.113.10.170"
      CSRF_TRUSTED_ORIGINS: "https://task.abcvip.site,https://148.113.10.170"
      SESSION_COOKIE_SECURE: "True"
      SESSION_COOKIE_SAMESITE: "None"
      CSRF_COOKIE_SECURE: "True"
      CSRF_COOKIE_SAMESITE: "None"
      SECURE_PROXY_SSL_HEADER: "HTTP_X_FORWARDED_PROTO,https"
      USE_X_FORWARDED_HOST: "True"
